name: Java CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: docker build -t integrationninjas/springboot-example .

      - name: Publish image to Docker Hub
        run: docker push integrationninjas/springboot-example:latest

  deploy:
    needs: build
    runs-on: [self-hosted]

    steps:
      - name: Pull Image from Docker Hub
        run: docker pull integrationninjas/springboot-example:latest

      - name: Delete old container if exists
        run: docker rm -f springboot-example-container || true

      - name: Run Docker container
        run: docker run -d -p 8080:8080 --name springboot-example-container integrationninjas/springboot-example
